[tool.isort]
profile = "black"
src_paths = [".", "database", "services", "utils", "api", "gui", "scripts"]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
known_first_party = ["database", "services", "utils", "api", "gui", "scripts"]
default_section = "THIRDPARTY"

[tool.black]
line-length = 88
target-version = ["py37", "py38", "py39"]
include_trailing_comma = true
skip-string-normalization = false

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = true
disallow_untyped_decorators = false
no_implicit_optional = true
strict_optional = true

[[tool.mypy.overrides]]
module = ["pandas.*", "matplotlib.*", "seaborn.*", "numpy.*"]
ignore_missing_imports = true
